### ISSUE TITLE
Add Contribution Guide

### ISSUE THREAD

**Issue by rahulkumaran** [rahulkumaran/sudocode#15]
**Is your feature request related to a problem? Please describe.**
Currently, there's no contribution guide. Create a `CONTRIBUTING.md` in the root directory of the repo so that people know how to make contributions to the repo. This will help in maintaining the quality of the repo.

**Describe the solution you'd like**
Create a CONTRIBUTING.md in the root directory.

**Comment by shreyk5** [comment]
I would like to work on this issue.

**Comment by rahulkumaran** [comment]
@shreyk5 this is a priority issue. Please complete it ASAP.

**Comment by shreyk5** [comment]
Made a pull request.
