### ISSUE TITLE
Add Pull request template

### ISSUE THREAD

**Issue by rahulkumaran** [rahulkumaran/sudocode#16]
**Is your feature request related to a problem? Please describe.**
Currently we don't have a PR Template and it's necessary to have so that we can check whether the PR meets the basic requirements. Will post links of a PR template that we could follow once someone has claimed this.

**Describe the solution you'd like**
Follow standard procedure to create a pr template

**Comment by deepak2431** [comment]
I would like to work on this.

**Comment by rahulkumaran** [comment]
Sure. You can begin to work @deepak2431 
Google first about how to create a PR template. Look at other major projects of FOSSASIA (https://github.com/fossasia) to get a better understanding too.
Create the PR Template in the `.github` directory.

Check this link out too https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by pieceofeden** [comment]
Can I work on this issue ??
