### ISSUE TITLE
rename sudocode.py as sudocode_c.py

### ISSUE THREAD

**Issue by rahulkumaran** [rahulkumaran/sudocode#18]
**Is your feature request related to a problem? Please describe.**
Looking at expanding this to other programming languages too. Hence, we need to know what file needs to be called and when a particular file needs to be called.

**Describe the solution you'd like**
Let's start calling each sudocode file as sudocode_<language>.py.
For example, currently we have the logic to convert pseudocode to C, so let's call it sudocode_c.py

**Comment by ayushk203** [comment]
I would like to work on it for python

**Comment by rahulkumaran** [comment]
Cool. Go for it @ayushk203

**Comment by ayushk203** [comment]
cleaner.py ->func(cleaner) we can check their whether it is sudocode_c or sudocode_cpp or sudocode_py etc and then as you have done for c and cpp we can do it for python or c++ or any other language

**Comment by siAyush** [comment]
hi, @ayushk203  I'm also thinking about the same idea can we work together.

**Comment by ayushk203** [comment]
I think aditya raj @AR786 is assigned for converting sudocode to python

**Comment by ayushk203** [comment]
my problem is simple we just need to know which file needs to be called

**Comment by ayushk203** [comment]
I too misunderstood this prblem with #19

**Comment by rahulkumaran** [comment]
@ayushk203, I'm just seeing that you said you want to convert pseudocode to python. That's already being done. Also, please remember one thing. Don't discuss about a different issue on a particular issue as it makes the entire thing confusing. If you want to work on this issue of just renaming the sudocode.py file to sudocode_c.py then please go ahead. If there's any other thing that you want to work on that's already not mentioned as an issue, then please do raise a new issue. Cheers!

**Comment by ayushk203** [comment]
that issue got solved?
because i was confused and was going to ask you?
ᐧ

**Comment by rahulkumaran** [comment]
You took a lot of time for an extremely trivial change that was hindering me from creating other issues. Please read the issue title and other related info in the issue carefully. I don't really see why it was that confusing. 

Anyway, I made the change myself now. Needed to create more issues accordingly. Please look out for other issues.

Cheers @ayushk203

**Comment by ayushk203** [comment]
that's probably because I was confused at begining with another issue.I'm
extremely sorry for that and I'll make sure that never happens again
ᐧ
