### ISSUE TITLE
Incorrect Functioning of Print Function : 

### ISSUE THREAD

**Issue by AviBomb** [rahulkumaran/sudocode#27]
I found an issue with the print command : Supposing we have a variable called temp in the code and we want to print the word "Temp" and then print the data inside temp there is no feature enabling us to do that it will only print the variable temp. Also yet another similar issue we face is that when we have two variables a and b in the program and we write in the pseudo-code print a+b instead of writing a+b in the program it writes the string "a+b" which makes it compulsory for us to create a temporary variable increasing both time and space complexity of the code. Both these issues can be sorted easily. I would love to work on this issue and will have a pull request ready by tomorrow

**Comment by rahulkumaran** [comment]
Sure Avi! Go ahead with it

**Comment by rahulkumaran** [comment]
Also, please follow Issue Template from next time.

**Comment by shamin1998** [comment]
perhaps there should be a completely different syntax for printing, to account for such things as printing
"a + b = <value of a+b>"
maybe similar to that of C++, cout
what do you think @rahulkumaran ?

**Comment by ShreyanshDarshan** [comment]
I would like to add to this issue the following:
1. Only 1 variable can be printed in a print statement.
2. There can't be text following the variable in the same print statement.

**Comment by ShreyanshDarshan** [comment]
@AviBomb if you've not started working on this issue then I would like to take this up.
