### ISSUE TITLE
Add .DS_Store to .gitignore

### ISSUE THREAD

**Issue by rahulkumaran** [rahulkumaran/sudocode#32]
**Describe the bug**
Currently, an unnecessary file appears in git status and that is .DS_Store
Add this to .gitignore

**To Reproduce**
1.  Create any file in Mac in the local repo.

**Expected behavior**
.DS_Store shouldn't appear when `git status` is run on terminal

**Comment by pieceofeden** [comment]
I want to claim this one

**Comment by pieceofeden** [comment]
![screenshot from 2018-12-08 09-42-55](https://user-images.githubusercontent.com/42468504/49681812-1d80fe00-face-11e8-9980-18f031dacdf7.png)
Is this okay ??

**Comment by rahulkumaran** [comment]
LGTM. Please send a PR
