### ISSUE TITLE
capture return value of function

### ISSUE THREAD

**Issue by rahulkumaran** [rahulkumaran/sudocode#33]
**Describe the bug**
Currently, in sudocode_c.py, the function can be called easily but it's not possible to capture the returned value from that function. Will be great to have someone work on capturing the returned value.

**Expected behavior**
The returned value must be captured in a variable.
If function `test` is called and the function returns an int value, then capture the returned val in an int var in the main body.

**Comment by ayushk203** [comment]
I can do it

**Comment by ayushk203** [comment]
I'll do it by tomorrow

**Comment by rahulkumaran** [comment]
Okay, sure! Go ahead. @ayushk203

**Comment by ayushk203** [comment]
to capture the return value we first need to know that whether that func. is of type void or not

**Comment by rahulkumaran** [comment]
Yeah, obviously. And I don't think that's a problem since we have this thing called `return_list` through which we can get whatever we want. Just that, rn it's set to an empty list when it encounters the `endfunction` keyword, but that statement can be removed and you can use that list to get the return type.

**Comment by ayushk203** [comment]
look thats why i'm little confused,actually we can have more than one function in pseudocode and then  first we have to do this return_list.append(line_elem) and at the time of call we have to search for in return_list whether that exist or not so there will be a lot of change inside call function

**Comment by ayushk203** [comment]
i've sent PR
