### ISSUE TITLE
Input file from Command line

### ISSUE THREAD

**Issue by harry-hov** [rahulkumaran/sudocode#4]
Add functionality to input "sudocode.txt" from command line.
So user dont need to go through code to open different "sudocode" file.

**e.g - $python3 main.py path/sudocode.txt**

**Comment by 7vikpeculiar** [comment]
Can i take it up ?

**Comment by harry-hov** [comment]
I can't got you. Please clear yourself

**Comment by harry-hov** [comment]
Actually, i already pushed PR regarding this issue yesterday. I used Command line arguments to input files. @rahulkumaran please take a look at PR #5 
Sure, next time i'll follow issue and PR template.
