### ISSUE TITLE
Add Build Badge

### ISSUE THREAD

**Issue by rahulkumaran** [rahulkumaran/sudocode#41]
**Is your feature request related to a problem? Please describe.**
Currently, we don't have a build badge in the readme. Add one to the readme.

**Describe the solution you'd like**
```
[![Build Status](https://travis-ci.com/rahulkumaran/sudocode.svg?branch=master)](https://travis-ci.com/rahulkumaran/sudocode)
```
Please add the above line to the readme.

**Comment by rahulkumaran** [comment]
[![Build Status](https://travis-ci.com/rahulkumaran/sudocode.svg?branch=master)](https://travis-ci.com/rahulkumaran/sudocode)

The badge to be got is supposed to look exactly like the one above.

**Comment by pieceofeden** [comment]
I will do it

**Comment by pieceofeden** [comment]
![screenshot from 2018-12-10 19-30-09](https://user-images.githubusercontent.com/42468504/49737137-10bcff80-fcb2-11e8-8647-ce55cb0384be.png)
Is this okay ? or should i bring the build passing to the next line

**Comment by pieceofeden** [comment]
@rahulkumaran  and i have rewritten the whole thing "python" as well as "chat on gitter" ?? since it's already there will github will ignore it and only add the build or will the python and chat on gitter added twice
