### ISSUE TITLE
Add code_of_conduct.md

### ISSUE THREAD

**Issue by rahulkumaran** [rahulkumaran/sudocode#46]
**Is your feature request related to a problem? Please describe.**
No file describing CoC is available on the repository now. Would be great to have one.

**Describe the solution you'd like**
Create a CODE_OF_CONDUCT.md in the root directory of the repo. Go through usual Code Of Conduct files in other major projects and tweak wherever necessary to make it fit for sudocode.

**Comment by pieceofeden** [comment]
I've a question regarding any compulsion for the number of lines to be added in the file. I went through many projects and some have like so many lines while some also have just one paragraph

**Comment by pieceofeden** [comment]
![screenshot from 2018-12-11 21-01-48](https://user-images.githubusercontent.com/42468504/49810834-066d3500-fd88-11e8-945b-bfba3fba7e9c.png)
Is this okay ?? if it is whose email address should i give for reporting any unacceptable behavior

**Comment by pieceofeden** [comment]
Many major projects have project steward to determine if the code of conduct was violated or not and to take further actions against them

**Comment by rahulkumaran** [comment]
> ![screenshot from 2018-12-11 21-01-48](https://user-images.githubusercontent.com/42468504/49810834-066d3500-fd88-11e8-945b-bfba3fba7e9c.png)
> Is this okay ?? if it is whose email address should i give for reporting any unacceptable behavior

rahulkumaran313@gmail.com

**Comment by debajyotidasgupta** [comment]
I have also prepared a CoC.md file.

![screenshot from 2018-12-12 12-32-32](https://user-images.githubusercontent.com/23581364/49852494-4412a200-fe0a-11e8-98f8-cb5c05fbe23a.png)
