### ISSUE TITLE
tags describing project

### ISSUE THREAD

**Issue by debajyotidasgupta** [rahulkumaran/sudocode#7]
some tags describing the project in README.md would help readers and the would also get the communication channel

**Comment by debajyotidasgupta** [comment]
[![forthebadge made-with-python](http://ForTheBadge.com/images/badges/made-with-python.svg)](https://www.python.org/)<br>
[![Gitter](https://img.shields.io/gitter/room/:user/:repo.svg)](https://gitter.im/Ossprojects4dev/sudocode)<br>
I added the above two tags for description

**Comment by rahulkumaran** [comment]
Looks like a good issue.
